ARG PROJECT
ARG PROJECT_ARCH
FROM $PROJECT-$PROJECT_ARCH-debian-builder
ARG GNU=https://ftpmirror.gnu.org/
ENV GNU=$GNU

WORKDIR /lfs
COPY scripts/environment.sh /lfs/
COPY scripts/5.5-glibc.sh /lfs/
COPY patches/binutils* /lfs/patches/
RUN ./5.5-glibc.sh