ARG PROJECT
ARG PROJECT_ARCH

FROM $PROJECT-$PROJECT_ARCH-binutils as binutils
FROM $PROJECT-$PROJECT_ARCH-debian-builder
COPY --from=binutils /lfs/tools /lfs/tools

WORKDIR /lfs
COPY scripts/environment.sh /lfs/
COPY scripts/5.3-gcc.sh /lfs/
RUN ./5.3-gcc.sh