ARG PROJECT
ARG PROJECT_ARCH
FROM $PROJECT-$PROJECT_ARCH-debian-builder as debian-builder
FROM $PROJECT-$PROJECT_ARCH-gcc as gcc
FROM debian:sid
COPY --from=gcc /lfs/logs/ /lfs/logs/
COPY --from=debian-builder /lfs/logs/ /lfs/logs/

