ARG PROJECT
ARG PROJECT_ARCH

FROM $PROJECT-$PROJECT_ARCH-sources AS sources
FROM $PROJECT-$PROJECT_ARCH-debian-builder

COPY --from=sources /lfs/sources/ncurses-* /lfs/sources/

WORKDIR /lfs
COPY scripts/environment.sh /lfs/
COPY scripts/6.3.1-ncurses.sh /lfs/
RUN ./6.3.1-ncurses.sh