ARG PROJECT
ARG PROJECT_ARCH

FROM $PROJECT-$PROJECT_ARCH-sources as sources
FROM $PROJECT-$PROJECT_ARCH-gcc as gcc
FROM $PROJECT-$PROJECT_ARCH-debian-builder

COPY --from=sources /lfs/sources/glibc* /lfs/sources/
COPY --from=sources /lfs/sources/linux* /lfs/sources/
COPY --from=gcc /lfs/tools /lfs/tools

ARG PROJECT_ARCH
ENV PROJECT_ARCH=$PROJECT_ARCH

WORKDIR /lfs
COPY scripts/environment.sh /lfs/
COPY scripts/5.5-glibc.sh /lfs/
COPY patches/glibc* /lfs/patches/
RUN ./5.5-glibc.sh
