FROM debian:sid AS debian-builder
ARG GNU=https://ftpmirror.gnu.org/
ENV GNU=$GNU
WORKDIR /lfs
COPY scripts/environment.sh /lfs/
COPY scripts/0-prereqs.sh /lfs/
#Yep, I'm installing bsdextrautils just for 'column'
RUN apt update; apt -y install --no-install-recommends bsdextrautils xz-utils gcc g++ bison make curl ca-certificates patch less texinfo
RUN ./0-prereqs.sh