ARG PROJECT
ARG PROJECT_ARCH

FROM $PROJECT-$PROJECT_ARCH-sources AS sources
FROM $PROJECT-$PROJECT_ARCH-debian-builder

COPY --from=sources /lfs/sources/binutils-* /lfs/sources/

WORKDIR /lfs
COPY scripts/environment.sh /lfs/
COPY scripts/5.2-binutils.sh /lfs/
RUN ./5.2-binutils.sh
