FROM debian:sid
#We don't want the deb files and lists to get removed as they are by default
RUN rm /etc/apt/apt.conf.d/docker-clean
RUN apt update && apt upgrade -y --download-only
RUN apt -y --download-only --no-install-recommends install \ 
bsdextrautils xz-utils gcc g++ bison make curl ca-certificates patch less texinfo wget python3 gawk file

#TODO: check if `file` was actually specified in the LFS book
#TODO: package-cache probably doesn't need to be separate from debian-builder
