FROM debian:sid

RUN mkdir -p /lfs/sources
RUN apt update && apt -y install aria2
WORKDIR /lfs/sources
RUN aria2c https://www.linuxfromscratch.org/lfs/downloads/development/wget-list
#TODO: split patches out of this list and put them in /lfs/patches
RUN aria2c -i wget-list
#TODO: check sha256sum of list / etag and flag if updated
